# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0 # Using a recent, stable version of mypy
    hooks:
    -   id: mypy
        # It's crucial to list dependencies that provide type hints here.
        # This ensures mypy can find and use them in its isolated environment.
        additional_dependencies:
          - "pandas-stubs"
          - "types-PyYAML"
          - "types-requests"
          - "types-tqdm"
          - "pandera"
          - "streamlit"
