# setup.py
from setuptools import setup, find_packages

# A list of dependencies for the project
install_deps = [
    "pandas",
    "polars",
    "xgboost",
    "optuna",
    "joblib",
    "PyYAML",
    "requests",
    "betfairlightweight",
    "flumine",  # Added missing dependency
    "pandera",
    "orjson",
    "bz2file",
    "thefuzz",
    "rapidfuzz",
    "python-Levenshtein",
    "scikit-learn",
    "unidecode",
    "hydra-core",
    "omegaconf",
    "matplotlib",
    "seaborn",
    "streamlit",
    "flake8",
    "mypy",
    "pandas-stubs",
    "types-PyYAML",
    "types-requests",
    "pytest",
    "black",
    "ruff",
    "pre-commit",
    "google-cloud-storage",
    "lightgbm",
    "typer[all]",
]

setup(
    name="tennis_betting_model",
    version="1.3.0",
    author="Luca Panozzo",
    author_email="luca.panozzo13@gmail.com",
    description="An automated trading bot for the Betfair Tennis exchange.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/puntingpro/tennis-betting-model",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.9",
    install_requires=install_deps,
    entry_points={"console_scripts": ["tennis-value-bot=main:main"]},
    classifiers=[
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
