defaults:
  model_file: models/xgb_model.joblib

tournaments:
  - label: ausopen_2024_atp
    tour: atp
    tournament: australian_open
    year: 2024
    start_date: "2024-01-14"
    end_date: "2024-01-28"
    snapshots_csv: parsed/betfair_ausopen_2024_atp_snapshots.csv
    sackmann_csv: data/tennis_atp/atp_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: hard
    tier: grand_slam
    # Example of specifying a flat staking strategy for this tournament run
    staking_strategy: "flat"
    flat_stake_unit: 15.0

  - label: ausopen_2024_wta
    tour: wta
    tournament: australian_open
    year: 2024
    start_date: "2024-01-14"
    end_date: "2024-01-28"
    snapshots_csv: parsed/betfair_ausopen_2024_wta_snapshots.csv
    sackmann_csv: data/tennis_wta/wta_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: hard
    tier: grand_slam
    # This tournament will use the default 'kelly' strategy since it's not specified

  - label: frenchopen_2024_atp
    tour: atp
    tournament: roland_garros
    year: 2024
    start_date: "2024-05-26"
    end_date: "2024-06-09"
    snapshots_csv: parsed/betfair_frenchopen_2024_atp_snapshots.csv
    sackmann_csv: data/tennis_atp/atp_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: clay
    tier: grand_slam

  - label: frenchopen_2024_wta
    tour: wta
    tournament: roland_garros
    year: 2024
    start_date: "2024-05-26"
    end_date: "2024-06-09"
    snapshots_csv: parsed/betfair_frenchopen_2024_wta_snapshots.csv
    sackmann_csv: data/tennis_wta/wta_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: clay
    tier: grand_slam

  - label: wimbledon_2024_atp
    tour: atp
    tournament: wimbledon
    year: 2024
    start_date: "2024-07-01"
    end_date: "2024-07-14"
    snapshots_csv: parsed/betfair_wimbledon_2024_atp_snapshots.csv
    sackmann_csv: data/tennis_atp/atp_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: grass
    tier: grand_slam

  - label: wimbledon_2024_wta
    tour: wta
    tournament: wimbledon
    year: 2024
    start_date: "2024-07-01"
    end_date: "2024-07-14"
    snapshots_csv: parsed/betfair_wimbledon_2024_wta_snapshots.csv
    sackmann_csv: data/tennis_wta/wta_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.2
    surface: grass
    tier: grand_slam

  - label: usopen_2024_atp
    tour: atp
    tournament: us_open
    year: 2024
    start_date: "2024-08-26"
    end_date: "2024-09-08"
    snapshots_csv: parsed/betfair_usopen_2024_atp_snapshots.csv
    sackmann_csv: data/tennis_atp/atp_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: hard
    tier: grand_slam

  - label: usopen_2024_wta
    tour: wta
    tournament: us_open
    year: 2024
    start_date: "2024-08-26"
    end_date: "2024-09-08"
    snapshots_csv: parsed/betfair_usopen_2024_wta_snapshots.csv
    sackmann_csv: data/tennis_wta/wta_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.2
    surface: hard
    tier: grand_slam

  - label: indianwells_2024_atp
    tour: atp
    tournament: indian_wells
    year: 2024
    start_date: "2024-03-06"
    end_date: "2024-03-17"
    snapshots_csv: parsed/betfair_indianwells_2024_atp_snapshots.csv
    sackmann_csv: data/tennis_atp/atp_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: hard
    tier: masters

  - label: indianwells_2024_wta
    tour: wta
    tournament: indian_wells
    year: 2024
    start_date: "2024-03-06"
    end_date: "2024-03-17"
    snapshots_csv: parsed/betfair_indianwells_2024_wta_snapshots.csv
    sackmann_csv: data/tennis_wta/wta_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: hard
    tier: masters

  - label: miami_2024_atp
    tour: atp
    tournament: miami
    year: 2024
    start_date: "2024-03-20"
    end_date: "2024-03-31"
    snapshots_csv: parsed/betfair_miami_2024_atp_snapshots.csv
    sackmann_csv: data/tennis_atp/atp_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: hard
    tier: masters

  - label: miami_2024_wta
    tour: wta
    tournament: miami
    year: 2024
    start_date: "2024-03-20"
    end_date: "2024-03-31"
    snapshots_csv: parsed/betfair_miami_2024_wta_snapshots.csv
    sackmann_csv: data/tennis_wta/wta_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: hard
    tier: masters

  - label: madrid_2024_atp
    tour: atp
    tournament: madrid
    year: 2024
    start_date: "2024-04-22"
    end_date: "2024-05-05"
    snapshots_csv: parsed/betfair_madrid_2024_atp_snapshots.csv
    sackmann_csv: data/tennis_atp/atp_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: clay
    tier: masters

  - label: madrid_2024_wta
    tour: wta
    tournament: madrid
    year: 2024
    start_date: "2024-04-22"
    end_date: "2024-05-05"
    snapshots_csv: parsed/betfair_madrid_2024_wta_snapshots.csv
    sackmann_csv: data/tennis_wta/wta_matches_2024.csv
    alias_csv: configs/player_aliases.csv
    ev_threshold: 0.3
    surface: clay
    tier: masters