name: Python CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # FIX: Add this step to install the project itself
      - name: Install project in editable mode
        run: pip install -e .

      - name: Lint with Black
        run: black --check src main.py tests

      - name: Lint with Ruff
        run: ruff check src main.py tests

      - name: Type-check with MyPy
        run: mypy src main.py tests

      - name: Run tests and report coverage
        # FIX: Removed PYTHONPATH=src from the command
        run: |
          pytest --cov=src --cov-report=xml --maxfail=1 --disable-warnings -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
