name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # --- REFACTOR: Consolidated dependency installation ---
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . # Installs package from setup.py and its dependencies

    # --- REFACTOR: Replaced flake8 with a single ruff command ---
    - name: Run linter and type checker
      run: |
        # Ruff handles linting, complexity, and line length checks
        ruff check src/tennis_betting_model/ tests/
        mypy src/tennis_betting_model/

    - name: Run tests with pytest
      run: |
        pytest tests/
