# /.github/workflows/run_stream.yml
name: Run PuntingPro Live Stream Bot
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  run-live-stream:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Download Processed Data and Models from GCS
        run: |
          mkdir -p ./data/processed ./models
          gcloud storage rsync -r gs://puntingpro-data-lucap/processed ./data/processed
          gcloud storage rsync -r gs://puntingpro-data-lucap/models ./models
      - name: Create Betfair Certs
        run: |
          mkdir -p certs
          echo "${{ secrets.BF_GHA_CERT }}" > certs/betfair.crt
          echo "${{ secrets.BF_GHA_KEY }}" > certs/betfair.key
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run the live streaming bot
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
          BF_USER: ${{ secrets.BF_USER }}
          BF_PASS: ${{ secrets.BF_PASS }}
          BF_APP_KEY: ${{ secrets.BF_APP_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run:
          python -u main.py stream
